---
- name: Configure Spring Ninja Box
  hosts: all
  sudo: true
  user: vagrant
  tasks:
    - name: "Atualiza pacotes e instala nginx"
      apt: name=nginx state=latest update_cache=yes install_recommends=yes

    - name: "add repo for java 8"
      apt_repository: repo='ppa:webupd8team/java' state=present 

    - name: set licence selected
      shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
      sudo: yes

    - name: set licence seen
      shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 seen true | /usr/bin/debconf-set-selections
      sudo: yes

    - name: install java 8
      apt: name=oracle-java8-installer state=latest update-cache=yes force=yes
      sudo: yes
    
    - name: "Copia configuração nginx.conf"
      copy: src=nginx.conf dest=/etc/nginx/
    
    - name: "cria diretorio do app"
      shell: mkdir -p /app-production
    
    - name: "copia jar"
      copy: src=ninja-box-0.0.1-SNAPSHOT.jar dest=/app-production

    - name: "executa aplicacao"
      shell: nohup java -jar /app-production/ninja-box-0.0.1-SNAPSHOT.jar --server.port=8081 &

    - name: "Reinicia o NGINX"
      shell: service nginx restart