- name: "update packages and install nginx"
  apt: name=nginx state=latest update_cache=yes install_recommends=yes

- name: Configure nginx - nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/
  notify: restart nginx