
---
- name: Configure spring boot ninja box
  hosts: all
  sudo: true
  roles:
    - { role: java, tags: ['java'] }
    - { role: defaults, tags: ['defaults'] } 
    - { role: nginx, tags: ['nginx'] }

    